### ISSUE TITLE
Connection refused from virtual data nodes

### ISSUE THREAD

**Issue by julwin** [exasol/spark-connector#132]
We have a setup going on where our DEV instance of Exasol (4 nodes) is running on one host and uses a different port for each virtual node (running in docker). E.g.:

n1 = host.ip:8563
n2 = host.ip:8564
n3 = host.ip:8565
n44 = host.ip:8566

Coming from [this example ](https://github.com/exasol/pyexasol/blob/master/examples/c13_dsn_parsing.py), it should be possible to connect to this kind of setup. 

Is it possible to do so using spark-connector? 

When trying to overload the "host" option in spark like so:
```
df.write.mode("overwrite")
        .format("exasol")
        .option(
            "host","host.ip/ABC:8899,host.ip/ABC:8900,host.ip/ABC:8901,host.ip/ABC:8902"
        )
        # .option("port", conn.port)
        .option("username", conn.login)
        .option("password", conn.password)
        .option("create_table", "true")
        .option("table", "TESTING.test")
        # .option("fingerprint", conn.extra_dejson["fingerprint"])
        .save()
```

I get the following error message (understandably):
`pyspark.sql.utils.IllegalArgumentException: E-SEC-4: The host value is not an IPv4 address. The host value should be an IPv4 address of the first Exasol datanode.`

The stacktrace of the error I'm getting:

```
org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 2.0 failed 1 times, most recent failure: Lost task 0.0 in stage 2.0 (TID 6) (test-exasol-spark-task-e01be1a5bd4544378e47ac063b3f1e28 executor driver): com.exasol.jdbc.ConnectFailed: java.net.ConnectException: Connection refused (Connection refused)
	at com.exasol.jdbc.AbstractEXAConnection.connectAndLogin(AbstractEXAConnection.java:2338)
	at com.exasol.jdbc.AbstractEXAConnection.setupConnection(AbstractEXAConnection.java:1616)
	at com.exasol.jdbc.AbstractEXAConnection.Connect(AbstractEXAConnection.java:1482)
	at com.exasol.jdbc.AbstractEXAConnection.<init>(AbstractEXAConnection.java:556)
	at com.exasol.jdbc.EXAConnection.<init>(EXAConnection.java:37)
	at com.exasol.jdbc.EXADriver.connect(EXADriver.java:225)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
	at com.exasol.spark.util.ExasolConnectionManager$.createConnection(ExasolConnectionManager.scala:253)
	at com.exasol.spark.util.ExasolConnectionManager$.makeConnection(ExasolConnectionManager.scala:269)
	at com.exasol.spark.util.ExasolConnectionManager.subConnection(ExasolConnectionManager.scala:101)
	at com.exasol.spark.writer.ExasolWriter.insertPartition(ExasolWriter.scala:74)
	at com.exasol.spark.DefaultSource.$anonfun$saveDataFrame$1(DefaultSource.scala:159)
	at com.exasol.spark.DefaultSource.$anonfun$saveDataFrame$1$adapted(DefaultSource.scala:159)
	at org.apache.spark.rdd.RDD.$anonfun$foreachPartition$2(RDD.scala:1011)
	at org.apache.spark.rdd.RDD.$anonfun$foreachPartition$2$adapted(RDD.scala:1011)
	at org.apache.spark.SparkContext.$anonfun$runJob$5(SparkContext.scala:2268)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:136)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:548)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1504)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:551)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

Driver stacktrace:
	at org.apache.spark.scheduler.DAGScheduler.failJobAndIndependentStages(DAGScheduler.scala:2672)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2(DAGScheduler.scala:2608)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2$adapted(DAGScheduler.scala:2607)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
	at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:2607)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1(DAGScheduler.scala:1182)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1$adapted(DAGScheduler.scala:1182)
	at scala.Option.foreach(Option.scala:407)
	at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:1182)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:2860)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2802)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2791)
	at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:49)
	at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:952)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2228)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2249)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2268)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2293)
	at org.apache.spark.rdd.RDD.$anonfun$foreachPartition$1(RDD.scala:1011)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
	at org.apache.spark.rdd.RDD.withScope(RDD.scala:406)
	at org.apache.spark.rdd.RDD.foreachPartition(RDD.scala:1009)
	at com.exasol.spark.DefaultSource.saveDataFrame(DefaultSource.scala:159)
	at com.exasol.spark.DefaultSource.createRelation(DefaultSource.scala:103)
	at org.apache.spark.sql.execution.datasources.SaveIntoDataSourceCommand.run(SaveIntoDataSourceCommand.scala:47)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult$lzycompute(commands.scala:75)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult(commands.scala:73)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.executeCollect(commands.scala:84)
	at org.apache.spark.sql.execution.QueryExecution$$anonfun$eagerlyExecuteCommands$1.$anonfun$applyOrElse$1(QueryExecution.scala:98)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$6(SQLExecution.scala:109)
	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:169)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$1(SQLExecution.scala:95)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:779)
	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:64)
	at org.apache.spark.sql.execution.QueryExecution$$anonfun$eagerlyExecuteCommands$1.applyOrElse(QueryExecution.scala:98)
	at org.apache.spark.sql.execution.QueryExecution$$anonfun$eagerlyExecuteCommands$1.applyOrElse(QueryExecution.scala:94)
	at org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$transformDownWithPruning$1(TreeNode.scala:584)
	at org.apache.spark.sql.catalyst.trees.CurrentOrigin$.withOrigin(TreeNode.scala:176)
	at org.apache.spark.sql.catalyst.trees.TreeNode.transformDownWithPruning(TreeNode.scala:584)
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.org$apache$spark$sql$catalyst$plans$logical$AnalysisHelper$$super$transformDownWithPruning(LogicalPlan.scala:30)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.transformDownWithPruning(AnalysisHelper.scala:267)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.transformDownWithPruning$(AnalysisHelper.scala:263)
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.transformDownWithPruning(LogicalPlan.scala:30)
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.transformDownWithPruning(LogicalPlan.scala:30)
	at org.apache.spark.sql.catalyst.trees.TreeNode.transformDown(TreeNode.scala:560)
	at org.apache.spark.sql.execution.QueryExecution.eagerlyExecuteCommands(QueryExecution.scala:94)
	at org.apache.spark.sql.execution.QueryExecution.commandExecuted$lzycompute(QueryExecution.scala:81)
	at org.apache.spark.sql.execution.QueryExecution.commandExecuted(QueryExecution.scala:79)
	at org.apache.spark.sql.execution.QueryExecution.assertCommandExecuted(QueryExecution.scala:116)
	at org.apache.spark.sql.DataFrameWriter.runCommand(DataFrameWriter.scala:860)
	at org.apache.spark.sql.DataFrameWriter.saveToV1Source(DataFrameWriter.scala:390)
	at org.apache.spark.sql.DataFrameWriter.saveInternal(DataFrameWriter.scala:363)
	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:247)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: com.exasol.jdbc.ConnectFailed: java.net.ConnectException: Connection refused (Connection refused)
	at com.exasol.jdbc.AbstractEXAConnection.connectAndLogin(AbstractEXAConnection.java:2338)
	at com.exasol.jdbc.AbstractEXAConnection.setupConnection(AbstractEXAConnection.java:1616)
	at com.exasol.jdbc.AbstractEXAConnection.Connect(AbstractEXAConnection.java:1482)
	at com.exasol.jdbc.AbstractEXAConnection.<init>(AbstractEXAConnection.java:556)
	at com.exasol.jdbc.EXAConnection.<init>(EXAConnection.java:37)
	at com.exasol.jdbc.EXADriver.connect(EXADriver.java:225)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
	at com.exasol.spark.util.ExasolConnectionManager$.createConnection(ExasolConnectionManager.scala:253)
	at com.exasol.spark.util.ExasolConnectionManager$.makeConnection(ExasolConnectionManager.scala:269)
	at com.exasol.spark.util.ExasolConnectionManager.subConnection(ExasolConnectionManager.scala:101)
	at com.exasol.spark.writer.ExasolWriter.insertPartition(ExasolWriter.scala:74)
	at com.exasol.spark.DefaultSource.$anonfun$saveDataFrame$1(DefaultSource.scala:159)
	at com.exasol.spark.DefaultSource.$anonfun$saveDataFrame$1$adapted(DefaultSource.scala:159)
	at org.apache.spark.rdd.RDD.$anonfun$foreachPartition$2(RDD.scala:1011)
	at org.apache.spark.rdd.RDD.$anonfun$foreachPartition$2$adapted(RDD.scala:1011)
	at org.apache.spark.SparkContext.$anonfun$runJob$5(SparkContext.scala:2268)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:136)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:548)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1504)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:551)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	... 1 more
```

**Comment by morazow** [comment]
Hello @julwin,

Thanks for the feedback!

Unfortunately, it is not possible to use the connection string as you provided. The spark connector uses Exasol JDBC sub-connections, that requires an IPv4 address of the first node to establish parallel connections to the datanodes.

**Comment by julwin** [comment]
Hi @morazow,

just for my understanding:
- The master node is communicating the connection strings for the data nodes automatically?
- Are the port ranges 20000-21000 required for sub connections to work?
- Does the port of the master node matter? Because we are not using 8563 in some environments..

**Comment by morazow** [comment]
Hello @julwin,

1) Yes, the Spark driver will communicate with using initial JDBC connection, e.g, host:port connection string.
2) Yes correct. These port ranges should be reachable.
3) No, if the regular JDBC connection works, that should be fine.

**Comment by morazow** [comment]
Hello @julwin,

Can we close this ticket? Please let me know if you have any other questions.
